/* GssParserCCTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. GssParserCCTokenManager.java */
package com.google.common.css.compiler.ast;
import com.google.common.base.CharMatcher;
import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Lists;
import com.google.common.css.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.regex.Pattern;

/** Token Manager. */
@SuppressWarnings("unused")public class GssParserCCTokenManager implements GssParserCCConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x40L) != 0L)
            return 139;
         if ((active0 & 0x4000000080L) != 0L)
            return 176;
         if ((active0 & 0x10000L) != 0L)
            return 288;
         if ((active0 & 0x8000000L) != 0L)
            return 3;
         if ((active0 & 0x20L) != 0L)
            return 5;
         if ((active0 & 0x10L) != 0L)
            return 9;
         return -1;
      case 1:
         if ((active0 & 0x4000000000L) != 0L)
            return 183;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         return jjStartNfaWithStates_0(0, 16, 288);
      case 37:
         return jjStopAtPos(0, 17);
      case 40:
         return jjStopAtPos(0, 11);
      case 41:
         return jjStopAtPos(0, 12);
      case 42:
         return jjStartNfaWithStates_0(0, 5, 5);
      case 44:
         return jjStopAtPos(0, 15);
      case 45:
         jjmatchedKind = 7;
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 46:
         return jjStartNfaWithStates_0(0, 4, 9);
      case 47:
         return jjStartNfaWithStates_0(0, 6, 139);
      case 58:
         return jjStopAtPos(0, 3);
      case 59:
         return jjStopAtPos(0, 2);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 61:
         return jjStopAtPos(0, 8);
      case 91:
         return jjStopAtPos(0, 9);
      case 93:
         return jjStopAtPos(0, 10);
      case 94:
         return jjStartNfaWithStates_0(0, 27, 3);
      case 123:
         return jjStopAtPos(0, 13);
      case 125:
         return jjStopAtPos(0, 14);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 45:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 62:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(2, 38);
         break;
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(3, 37);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 288;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 58)
                        kind = 58;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if ((0x100003600L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     { jjCheckNAddStates(3, 13); }
                  }
                  else if (curChar == 45)
                     { jjAddStates(14, 16); }
                  else if (curChar == 36)
                     { jjAddStates(17, 18); }
                  else if (curChar == 47)
                     { jjCheckNAddTwoStates(139, 154); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(19, 21); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(22, 24); }
                  else if (curChar == 33)
                     { jjCheckNAddTwoStates(13, 22); }
                  else if (curChar == 35)
                     { jjCheckNAdd(11); }
                  else if (curChar == 46)
                     { jjCheckNAdd(9); }
                  else if (curChar == 62)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  else if (curChar == 43)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 5;
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 1;
                  if (curChar == 45)
                     { jjAddStates(25, 26); }
                  break;
               case 183:
                  if (curChar == 45)
                     { jjCheckNAdd(184); }
                  break;
               case 288:
               case 13:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(13, 22); }
                  break;
               case 139:
                  if (curChar != 42)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddStates(27, 32); }
                  break;
               case 176:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(183, 184); }
                  break;
               case 1:
                  if (curChar == 38 && kind > 30)
                     kind = 30;
                  break;
               case 3:
                  if (curChar == 61 && kind > 33)
                     kind = 33;
                  break;
               case 4:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if (curChar == 61 && kind > 35)
                     kind = 35;
                  break;
               case 6:
                  if (curChar == 43 && kind > 49)
                     kind = 49;
                  break;
               case 7:
                  if (curChar == 62 && kind > 50)
                     kind = 50;
                  break;
               case 8:
                  if (curChar == 46)
                     { jjCheckNAdd(9); }
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAdd(9); }
                  break;
               case 10:
                  if (curChar == 35)
                     { jjCheckNAdd(11); }
                  break;
               case 11:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  { jjCheckNAdd(11); }
                  break;
               case 12:
                  if (curChar == 33)
                     { jjCheckNAddTwoStates(13, 22); }
                  break;
               case 23:
                  if (curChar == 34)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 24:
                  if ((0xfffffffbffffcbffL & l) != 0L)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 25:
                  if (curChar == 34 && kind > 61)
                     kind = 61;
                  break;
               case 27:
                  if (curChar == 10)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 28:
               case 32:
                  if (curChar == 13)
                     { jjCheckNAdd(27); }
                  break;
               case 29:
                  if ((0x3400L & l) != 0L)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 30:
                  if ((0xfc00ffffffffcbffL & l) != 0L)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(33, 38); }
                  break;
               case 33:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(39, 47); }
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(48, 52); }
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(53, 58); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(59, 65); }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(66, 73); }
                  break;
               case 39:
                  if (curChar == 39)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 40:
                  if ((0xffffff7fffffcbffL & l) != 0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 41:
                  if (curChar == 39 && kind > 62)
                     kind = 62;
                  break;
               case 43:
                  if (curChar == 10)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 44:
               case 48:
                  if (curChar == 13)
                     { jjCheckNAdd(43); }
                  break;
               case 45:
                  if ((0x3400L & l) != 0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 46:
                  if ((0xfc00ffffffffcbffL & l) != 0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(74, 79); }
                  break;
               case 49:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(80, 88); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(89, 93); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(94, 99); }
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(100, 106); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(107, 114); }
                  break;
               case 56:
                  if (curChar == 40)
                     { jjCheckNAddStates(115, 117); }
                  break;
               case 57:
                  if ((0xfffffc7a00000000L & l) != 0L)
                     { jjCheckNAddStates(118, 120); }
                  break;
               case 58:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(58, 59); }
                  break;
               case 59:
                  if (curChar == 41 && kind > 63)
                     kind = 63;
                  break;
               case 60:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddStates(121, 124); }
                  break;
               case 67:
                  if (curChar == 40 && kind > 68)
                     kind = 68;
                  break;
               case 71:
                  if (curChar == 40 && kind > 69)
                     kind = 69;
                  break;
               case 76:
                  if (curChar == 40 && kind > 70)
                     kind = 70;
                  break;
               case 81:
                  if (curChar == 40 && kind > 71)
                     kind = 71;
                  break;
               case 84:
                  if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(125, 127); }
                  break;
               case 86:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(128, 131); }
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAdd(89); }
                  break;
               case 91:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddTwoStates(89, 90); }
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(132, 134); }
                  break;
               case 93:
                  if (curChar != 63)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if (curChar != 63)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(135, 138); }
                  break;
               case 95:
                  if (curChar == 63 && kind > 73)
                     kind = 73;
                  break;
               case 96:
                  if (curChar != 63)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAdd(95); }
                  break;
               case 97:
                  if (curChar != 63)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddTwoStates(95, 96); }
                  break;
               case 98:
                  if (curChar != 63)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(139, 141); }
                  break;
               case 99:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(142, 147); }
                  break;
               case 100:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddTwoStates(86, 93); }
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(148, 150); }
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(151, 154); }
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(155, 159); }
                  break;
               case 105:
                  if (curChar == 45)
                     { jjAddStates(25, 26); }
                  break;
               case 109:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 119:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 132:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 135:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 136:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  { jjCheckNAdd(136); }
                  break;
               case 137:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(137, 8); }
                  break;
               case 138:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(139, 154); }
                  break;
               case 140:
                  if ((0xffff7bffffffffffL & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddStates(27, 32); }
                  break;
               case 141:
                  if (curChar != 47)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddStates(27, 32); }
                  break;
               case 142:
                  if (curChar != 47)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddTwoStates(144, 145); }
                  break;
               case 143:
                  if (curChar != 10)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddTwoStates(144, 145); }
                  break;
               case 144:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddTwoStates(144, 145); }
                  break;
               case 146:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 147:
                  if (curChar != 42)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddStates(160, 165); }
                  break;
               case 148:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(148, 140); }
                  break;
               case 149:
                  if (curChar != 42)
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjCheckNAddStates(166, 169); }
                  break;
               case 151:
                  if (curChar == 47 && kind > 52)
                     kind = 52;
                  break;
               case 157:
                  if (curChar == 61 && kind > 36)
                     kind = 36;
                  break;
               case 159:
                  if (curChar == 61 && kind > 32)
                     kind = 32;
                  break;
               case 160:
                  if (curChar == 36)
                     { jjAddStates(17, 18); }
                  break;
               case 161:
                  if (curChar == 61 && kind > 34)
                     kind = 34;
                  break;
               case 163:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 164:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  { jjCheckNAddStates(3, 13); }
                  break;
               case 165:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  { jjCheckNAdd(165); }
                  break;
               case 166:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(166, 167); }
                  break;
               case 167:
                  if (curChar == 45)
                     { jjCheckNAdd(168); }
                  break;
               case 168:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAdd(168); }
                  break;
               case 169:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(169, 6); }
                  break;
               case 170:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(170, 7); }
                  break;
               case 171:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(171, 172); }
                  break;
               case 173:
                  if ((0x100003600L & l) != 0L)
                     { jjCheckNAddTwoStates(173, 174); }
                  break;
               case 174:
                  if (curChar == 47)
                     { jjCheckNAdd(154); }
                  break;
               case 175:
                  if (curChar == 45)
                     { jjAddStates(14, 16); }
                  break;
               case 177:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 178:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 180:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(170, 172); }
                  break;
               case 181:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(177, 181); }
                  break;
               case 185:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 186:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 187;
                  break;
               case 188:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(173, 175); }
                  break;
               case 189:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddTwoStates(185, 189); }
                  break;
               case 191:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 192:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 194:
                  if (curChar == 40 && kind > 74)
                     kind = 74;
                  break;
               case 195:
                  if ((0x3ff200000000000L & l) != 0L)
                     { jjCheckNAddStates(176, 179); }
                  break;
               case 196:
                  if ((0x3ff200000000000L & l) != 0L)
                     { jjCheckNAddStates(180, 182); }
                  break;
               case 227:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 232:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 234:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 235:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 237:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddStates(183, 185); }
                  break;
               case 238:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddTwoStates(234, 238); }
                  break;
               case 239:
                  if (curChar == 45)
                     { jjAddStates(186, 189); }
                  break;
               case 248:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 247;
                  break;
               case 263:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 275:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 286:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 285;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 66)
                        kind = 66;
                     { jjCheckNAddStates(190, 194); }
                  }
                  else if (curChar == 64)
                     { jjAddStates(195, 202); }
                  else if (curChar == 126)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjstateSet[jjnewStateCnt++] = 159;
                  }
                  else if (curChar == 124)
                     { jjAddStates(203, 204); }
                  else if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if (curChar == 117)
                     { jjAddStates(205, 206); }
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 84;
                  else if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 82;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 78;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 73;
                  else if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 68;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 183:
               case 184:
               case 189:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddTwoStates(185, 189); }
                  break;
               case 288:
               case 22:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 139:
               case 154:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 176:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(180, 182); }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 66)
                        kind = 66;
                     { jjCheckNAddTwoStates(177, 181); }
                  }
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 121;
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 2:
                  if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if (curChar == 116 && kind > 60)
                     kind = 60;
                  break;
               case 15:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 24:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 26:
                  if (curChar == 92)
                     { jjAddStates(207, 210); }
                  break;
               case 30:
                  if ((0xffffff81ffffffffL & l) != 0L)
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 31:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(33, 38); }
                  break;
               case 34:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(39, 47); }
                  break;
               case 35:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(48, 52); }
                  break;
               case 36:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(53, 58); }
                  break;
               case 37:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(59, 65); }
                  break;
               case 38:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(66, 73); }
                  break;
               case 40:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 42:
                  if (curChar == 92)
                     { jjAddStates(211, 214); }
                  break;
               case 46:
                  if ((0xffffff81ffffffffL & l) != 0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 47:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(74, 79); }
                  break;
               case 50:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(80, 88); }
                  break;
               case 51:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(89, 93); }
                  break;
               case 52:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(94, 99); }
                  break;
               case 53:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(100, 106); }
                  break;
               case 54:
                  if ((0x7e00000000L & l) != 0L)
                     { jjCheckNAddStates(107, 114); }
                  break;
               case 55:
                  if (curChar == 110)
                     { jjCheckNAdd(56); }
                  break;
               case 57:
                  if ((0x7fffffffefffffffL & l) != 0L)
                     { jjAddStates(118, 120); }
                  break;
               case 61:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 62:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 68:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 69:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 72:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 73:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 77:
               case 106:
               case 116:
                  if (curChar == 108)
                     { jjCheckNAdd(75); }
                  break;
               case 78:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 82:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 83:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 85:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(125, 127); }
                  break;
               case 87:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(128, 131); }
                  break;
               case 89:
                  if ((0x7e0000007eL & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 90:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAdd(89); }
                  break;
               case 91:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddTwoStates(89, 90); }
                  break;
               case 92:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(132, 134); }
                  break;
               case 99:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(142, 147); }
                  break;
               case 100:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddTwoStates(86, 93); }
                  break;
               case 101:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(148, 150); }
                  break;
               case 102:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(151, 154); }
                  break;
               case 103:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  { jjCheckNAddStates(155, 159); }
                  break;
               case 104:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 107:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 110:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 117:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 120:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if (curChar == 117)
                     { jjAddStates(205, 206); }
                  break;
               case 124:
                  if (curChar == 108)
                     { jjCheckNAdd(56); }
                  break;
               case 125:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 120)
                     { jjCheckNAdd(56); }
                  break;
               case 127:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 133:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 140:
                  if (kind > 1)
                     kind = 1;
                  { jjAddStates(27, 32); }
                  break;
               case 150:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 152:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 153:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 155:
                  if (curChar == 124)
                     { jjAddStates(203, 204); }
                  break;
               case 156:
                  if (curChar == 124 && kind > 31)
                     kind = 31;
                  break;
               case 158:
                  if (curChar != 126)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 162:
               case 163:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAdd(163); }
                  break;
               case 172:
                  if (curChar == 126 && kind > 51)
                     kind = 51;
                  break;
               case 179:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(177, 180); }
                  break;
               case 180:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(170, 172); }
                  break;
               case 181:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(177, 181); }
                  break;
               case 187:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddTwoStates(185, 188); }
                  break;
               case 188:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(173, 175); }
                  break;
               case 190:
               case 196:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(180, 182); }
                  break;
               case 193:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(215, 217); }
                  break;
               case 195:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(176, 179); }
                  break;
               case 197:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(190, 194); }
                  break;
               case 198:
                  if (curChar == 64)
                     { jjAddStates(195, 202); }
                  break;
               case 199:
                  if (curChar == 116 && kind > 75)
                     kind = 75;
                  break;
               case 200:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 115 && kind > 76)
                     kind = 76;
                  break;
               case 204:
               case 240:
               case 255:
               case 267:
               case 278:
                  if (curChar == 101)
                     { jjCheckNAdd(203); }
                  break;
               case 205:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 101 && kind > 77)
                     kind = 77;
                  break;
               case 213:
                  if (curChar == 103)
                     { jjCheckNAdd(212); }
                  break;
               case 214:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 216:
                  if (curChar == 110 && kind > 77)
                     kind = 77;
                  break;
               case 217:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 99)
                     { jjCheckNAdd(212); }
                  break;
               case 225:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 228:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 233:
               case 238:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddTwoStates(234, 238); }
                  break;
               case 236:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddTwoStates(234, 237); }
                  break;
               case 237:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddStates(183, 185); }
                  break;
               case 241:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 249:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 256:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 262:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 264:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 265:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 264;
                  break;
               case 266:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 268:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 274:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 276:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 279:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 280:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 281:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 282:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 283:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 284:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 285:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 287:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 286;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(190, 194); }
                  break;
               case 183:
               case 184:
               case 189:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddTwoStates(185, 189); }
                  break;
               case 176:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 66)
                        kind = 66;
                     { jjCheckNAddTwoStates(177, 181); }
                  }
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(180, 182); }
                  break;
               case 11:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 24:
               case 30:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(22, 24); }
                  break;
               case 40:
               case 46:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 57:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(118, 120); }
                  break;
               case 140:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 1)
                     kind = 1;
                  { jjAddStates(27, 32); }
                  break;
               case 162:
               case 163:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAdd(163); }
                  break;
               case 179:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(177, 180); }
                  break;
               case 180:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddStates(170, 172); }
                  break;
               case 181:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 66)
                     kind = 66;
                  { jjCheckNAddTwoStates(177, 181); }
                  break;
               case 187:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddTwoStates(185, 188); }
                  break;
               case 188:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 67)
                     kind = 67;
                  { jjCheckNAddStates(173, 175); }
                  break;
               case 190:
               case 196:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(180, 182); }
                  break;
               case 193:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(215, 217); }
                  break;
               case 195:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddStates(176, 179); }
                  break;
               case 233:
               case 238:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddTwoStates(234, 238); }
                  break;
               case 236:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddTwoStates(234, 237); }
                  break;
               case 237:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 78)
                     kind = 78;
                  { jjCheckNAddStates(183, 185); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 288 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   136, 137, 8, 165, 166, 167, 169, 6, 170, 7, 171, 172, 173, 174, 176, 182, 
   190, 161, 162, 40, 41, 42, 24, 25, 26, 115, 122, 140, 141, 146, 144, 145, 
   147, 24, 32, 33, 25, 26, 34, 24, 35, 32, 33, 25, 26, 36, 37, 38, 
   24, 32, 33, 25, 26, 24, 35, 32, 33, 25, 26, 24, 35, 32, 33, 25, 
   26, 36, 24, 35, 32, 33, 25, 26, 36, 37, 40, 48, 49, 41, 42, 50, 
   40, 51, 48, 49, 41, 42, 52, 53, 54, 40, 48, 49, 41, 42, 40, 51, 
   48, 49, 41, 42, 40, 51, 48, 49, 41, 42, 52, 40, 51, 48, 49, 41, 
   42, 52, 53, 57, 59, 60, 57, 58, 59, 57, 58, 59, 60, 86, 93, 99, 
   89, 90, 91, 92, 89, 90, 91, 95, 96, 97, 98, 95, 96, 97, 100, 86, 
   93, 101, 102, 103, 100, 86, 93, 100, 86, 93, 101, 100, 86, 93, 101, 102, 
   148, 140, 149, 146, 144, 145, 149, 146, 144, 145, 177, 181, 180, 185, 189, 188, 
   191, 196, 194, 195, 191, 196, 194, 234, 238, 237, 254, 266, 277, 287, 177, 181, 
   191, 196, 194, 202, 211, 215, 223, 231, 232, 233, 239, 156, 157, 125, 134, 28, 
   29, 30, 31, 44, 45, 46, 47, 191, 194, 195, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, "\73", "\72", "\56", "\52", "\57", "\55", "\75", "\133", "\135", 
"\50", "\51", "\173", "\175", "\54", "\41", "\45", null, null, null, null, null, null, 
null, null, null, "\136", null, null, null, null, null, null, null, null, null, 
"\74\41\55\55", "\55\55\76", null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 79)
   {
      jjmatchedKind = 79;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public GssParserCCTokenManager(CharStream stream){


    input_stream = stream;
  }

  /** Constructor. */
  public GssParserCCTokenManager (CharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(CharStream stream)
  {
	
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 288; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit( CharStream stream, int lexState)
  {
  
    ReInit( stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfc1f207fc803fffdL, 0xfefeL, 
};
static final long[] jjtoSkip = {
   0x2L, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x2L, 0x0L, 
};
    protected CharStream  input_stream;

    private final int[] jjrounds = new int[288];
    private final int[] jjstateSet = new int[2 * 288];

    
    protected int curChar;
}
