name: 'Feature'

on:
  push:
    branches-ignore:
      - 'develop'
      - 'master'

jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:

      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build
        run: mvn clean compile

      - name: test
        run: mvn test
