name: 'Master'

on:
  push:
    branches:
      - 'master'

jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:

      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_FILE}}" > closure-stylesheets.asc.b64
          base64 -d closure-stylesheets.asc.b64 > closure-stylesheets.asc
          cat closure-stylesheets.asc | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: build
        run: mvn clean compile

      - name: test
        run: mvn test

      - name: package
        run: mvn package

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish to the Maven Central Repository
        run: |
          mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
